language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"

install:
    - pip install tox-travis

git:
  depth: false

script:
    - tox

after_success:
  - |
      if [ ! -f coverage.xml ]; then
          echo "No coverage.xml found; skipping sending coverage to couverture.io"
          return
      fi
      if [ $TRAVIS_PULL_REQUEST != false ]; then
          REAL_COMMIT=$(git log -n 1 $TRAVIS_COMMIT_RANGE --format="%H")
          PR_NUM=$TRAVIS_PULL_REQUEST
      else
          REAL_COMMIT=$TRAVIS_COMMIT
      fi
      curl \
          --verbose \
          --header "X-Couverture-Pull-Request: $PR_NUM" \
          --data-binary @coverage.xml \
          "https://app.couverture.io/coverage/github/aconrad/pycobertura/$REAL_COMMIT/$TOXENV"
